import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      {/* <head>
        <Script
          src="https://tapi.bale.ai/miniapp.js?3"
          strategy="beforeInteractive"
        />
      </head> */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
