server {
    listen 80;  # پورت ورودی
    server_name localhost;

    location / {
        proxy_pass http://192.168.1.4:3000;  # آدرس و پورت پروژه Next.js
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
